server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bigproject?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: root
        password: 64175812Timmy!
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            #?????
            initialSize: 5
            #???
            minIdle: 5
            #???
            maxActive: 20
            #??????????????????????????ms
            maxWait: 60000
            #?????????????????????????
            timeBetweenEvictionRunsMillis: 60000
            #????????????????
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            # ?????????filters????????sql?????
            #'wall'??????SpringBoot???log4j?????log4j2
            filters: stat,wall,log4j2
            #??PSCache??
            maxPoolPreparedStatementPerConnectionSize: 20
            useGlobalDataSourceStat: true
            # ??connectProperties?????mergeSql????SQL??
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
            # ??StatFilter
            web-stat-filter:
                #???false????true??
                enabled: true
                url-pattern: "/*"
                exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
            #??StatViewServlet
            stat-view-servlet:
                url-pattern: "/druid/*"
                #????ip
                allow: 127.0.0.1
                login-username: admin
                login-password: 123456
                #????ip
                deny: 192.168.1.102
                #??????
                reset-enable: true
                #??
                enabled: true
# Mybatis??
mybatis:
    # ??XML???????????????
    # type-aliases-package: com.example.demo3.pojo
    # ??MyBatis?xml??????
    mapper-locations: classpath:mapper/*.xml
    # ????uName?????u_name
    #map-underscore-to-camel-case: true
# ??sql
logging:
    level:
        com.example.demo.mapper: debug
