server:
  port: 9015
dubbo:
  application:
    name: Report-api-A
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
    #address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183
  scan:
    base-packages: com.example.api
